### ISSUE TITLE
Support missing Lexers

### ISSUE THREAD

**Issue by dail8859** [notepad-plus-plus/notepad-plus-plus#1258]
Scintilla provides _numerous_ lexers, most of which Notepad++ is not using. They are just sitting there...so why not take advantage of them! Below is a list of the `SCLEX_xxx` defines that are not used within the `ScintillaEditView::langNames` array. I don't know what most of them are or if they all are applicable but I'm sure many of them could be used. I'd like conformation from @donho that pull requests adding many of these lexers would be accepted. 
- [ ] SCLEX_A68K
- [ ] SCLEX_ABAQUS
- [ ] SCLEX_APDL
- [ ] SCLEX_AS
- [x] SCLEX_ASN1
- [ ] SCLEX_ASYMPTOTE
- [ ] SCLEX_AVE
- [x] SCLEX_AVS
- [x] SCLEX_BAAN - 02bdd11
- [ ] SCLEX_BIBTEX
- [x] SCLEX_BLITZBASIC
- [ ] SCLEX_BULLANT
- [ ] SCLEX_CLW
- [ ] SCLEX_CLWNOCASE
- [ ] SCLEX_CONF
- [x] SCLEX_CONTAINER - not applicable
- [x] SCLEX_CPPNOCASE - probably not applicable
- [x] SCLEX_CSOUND
- [ ] SCLEX_DMAP
- [ ] SCLEX_DMIS
- [ ] SCLEX_ECL
- [ ] SCLEX_EIFFEL
- [ ] SCLEX_EIFFELKW
- [x] SCLEX_ERLANG
- [ ] SCLEX_ERRORLIST
- [x] SCLEX_ESCRIPT
- [x] SCLEX_F77 - Implemented in #1381
- [ ] SCLEX_FLAGSHIP
- [x] SCLEX_FORTH
- [x] SCLEX_FREEBASIC
- [ ] SCLEX_GAP
- [x] SCLEX_IHEX - 6b6b812
- [ ] SCLEX_KVIRC
- [x] SCLEX_LATEX
- [ ] SCLEX_LITERATEHASKELL
- [ ] SCLEX_LOT
- [ ] SCLEX_LOUT
- [ ] SCLEX_MAGIK
- [ ] SCLEX_MARKDOWN - Related issue #1695
- [ ] SCLEX_METAPOST
- [x] SCLEX_MMIXAL
- [ ] SCLEX_MODULA
- [ ] SCLEX_MSSQL
- [ ] SCLEX_MYSQL
- [x] SCLEX_NIMROD
- [x] SCLEX_NNCRONTAB
- [ ] SCLEX_OBJC
- [ ] SCLEX_OCTAVE
- [ ] SCLEX_OPAL
- [x] SCLEX_OSCRIPT
- [ ] SCLEX_PHPSCRIPT
- [ ] SCLEX_PLM
- [ ] SCLEX_PO - PR #181 never merged
- [ ] SCLEX_POV - PR #181 never merged
- [ ] SCLEX_POWERBASIC
- [ ] SCLEX_POWERPRO
- [ ] SCLEX_PROGRESS
- [x] SCLEX_PUREBASIC
- [x] SCLEX_REBOL
- [x] SCLEX_REGISTRY
- [X] SCLEX_RUST - Relate issue #469
- [ ] SCLEX_SCRIPTOL
- [ ] SCLEX_SML
- [ ] SCLEX_SORCUS
- [ ] SCLEX_SPECMAN
- [x] SCLEX_SPICE
- [x] SCLEX_SREC - 6b6b812
- [ ] SCLEX_STTXT
- [ ] SCLEX_TACL
- [ ] SCLEX_TADS3
- [ ] SCLEX_TAL
- [ ] SCLEX_TCMD
- [x] SCLEX_TEHEX - 6b6b812
- [x] SCLEX_TXT2TAGS
- [ ] SCLEX_VBSCRIPT
- [x] SCLEX_VISUALPROLOG - 854acae
- [ ] SCLEX_XCODE

**Comment by sanastasiou** [comment]
Bump. It's a freebie :)

**Comment by Croydon** [comment]
:+1:

**Comment by dail8859** [comment]
@donho Thoughts on this?

**Comment by dail8859** [comment]
@donho

**Comment by PauloFrancaLacerda** [comment]
SCLEX_SCSS :)

**Comment by dail8859** [comment]
@PauloFrancaLacerda There's no such lexer as `SCLEX_SCSS` in any version of Scintilla.

**Comment by dail8859** [comment]
@donho

**Comment by donho** [comment]
@dail8859 Oups, sorry for not reading this request until now.
I agree to support all of them, OTOH we need a set of file to valide these lexer as well.

**Comment by donho** [comment]
BTW, by memory we need to enlarge the lang array as well.

**Comment by dail8859** [comment]
> we need a set of file to valide these lexer as well.

Yes I agree this would be good. Do you have any ideas? Are you thinking actually include example files in the repository or just simple tests until the lexer seems fine?

> BTW, by memory we need to enlarge the lang array as well.

Yes this was one of the things I noticed and wasn't sure what side effects increasing the lang array would cause.

Also, to anyone else reading this I'm not proposing I do all of these myself :) so feel free to help out.

**Comment by MAPJe71** [comment]
Any idea what has to be done besides the lang array and the example/test files?

**Comment by dail8859** [comment]
Unfortunately adding a new lexer is a bit tedious, and every time a new lexer is added all other PRs for lexers need fixed because there will be merge conficts :(

Usually about 10 files need modified. For example if you take a look [here](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/1439/files) you can see this pending PR for adding Visual Prolog.

**Comment by dail8859** [comment]
@donho Oh and also [some other](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/2ff03fe2507043f062475edadc53b46b6f4aef7c/PowerEditor/src/menuCmdID.h#L473) defines would need adjusted.

**Comment by Cyrillev91** [comment]
I have send PR #2469 Add template code for missing Lexer.

The goal is to facilitate the integration of missing support.
The next PR (send by other contributer and me) will update (only 4) files:
- Keyword list (stylers.model.xml)
- Colors (langs.model.xml)
- Updating the Language menu (Notepad_plus.rc)
- The name of lexer (ScintillaEditView.cpp)

I put all lexers missing in a language >> Partial Support menu (Beta) (I can change this if you want)

@donho if you want you can add the PR #1257 #1439 before mine, I would correct the conflict.
@dail8859 : I have adjuste define  (IDM_LANG_EXTERNAL, ...)
I added spice lexer for test my code.

Sorry for my English (it's google translator...)

**Comment by Cyrillev91** [comment]
Connect Scintilla Lexers to npp :

-    **asn1 (Abstract Syntax Notation One)** : https://fr.wikipedia.org/wiki/ASN.1#Exemple
-    **avs (AviSynth)** : http://avisynth.nl/index.php/Script_examples
-    **blitzbasic** : http://www.blitzbasic.com/bmdocs/command.php?name=Mid&ref=2d_cat
    http://www.blitzbasic.com/codearcs/codearcs.php?cat=8"
-   **csound** : http://www.csounds.com/manual/html/PrefaceGettingStarted.html
-    **erlang** : http://erlang.org/doc/man/file.html
    http://erlang.org/documentation/doc-5.3.6.13/doc/getting_started/getting_started.html"
-    **escript** : http://erlang.org/doc/man/escript.html
-    **forth** : http://wiki.c2.com/?ExampleForthCode
-    **freebasic** : http://www.freebasic.net/
-    **latex** : http://physics.clarku.edu/sip/tutorials/TeX/intro.html (Sample LaTeX file)
-    **mmixa**l : http://mmix.cs.hm.edu/examples/hello.html
-    **nimrod** : http://www.csse.monash.edu.au/~nimrod/nimrodportal/manual/planfileexamples.shtml
-    **nncrontab** : http://www.nncron.ru/help/EN/working/cron-format.htm
-    **oscript** : http://www.oscriptadventures.com/
-    **purebasic** : https://www.purebasic.com/documentation/reference/ide_form.html
-    **rebol** : http://www.rebol.net/cookbook/recipes/0031.html
-    **registry** : windows registry file
-    **rust** : http://rustbyexample.com/std_misc/file/open.html
-    **spice** : http://www.seas.upenn.edu/~jan/spice/spice.overview.html
-    **txt2tags** : https://github.com/txt2tags/txt2tags/blob/master/samples/sample.t2t

PR #2566

**Comment by oirfeodent** [comment]
SCLEX_BAAN - PR [#2696](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/2696)

**Comment by donho** [comment]
In master now: 02bdd11700e6fb225157aa59f1f5f1a453865cee

**Comment by Cyrillev91** [comment]
@dail8859 please update your first post
check : 
-  SCLEX_IHEX          in master 6b6b812
-  SCLEX_SREC          in master 6b6b812
-  SCLEX_TEHEX         in master 6b6b812
-  SCLEX_VISUALPROLOG  in master 854acae
-  SCLEX_BAAN          in master 02bdd11

**Comment by MetaChuh** [comment]
@dail8859 
what's the status on that as of today ?

**Comment by dail8859** [comment]
Pretty much as the first comment shows. But again if the issue isnt going anywhere then no point in having it open.
